---
# defaults file for adriagalin.motd

ag_motd_add_footer: false

ag_motd_sysadmins_signature: Random system administrators
ag_motd_sysadmins_email: random@random.com

ag_motd_info:
  - " FQDN:    ": "{{ ansible_fqdn }}"
  - " Distro:  ": "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
  - " Virtual: ": "{{ 'YES' if ansible_virtualization_role == 'guest' else 'NO' }}\n"
  - " CPUs:    ": "{{ ansible_processor_vcpus }}"
  - " RAM:     ": "{{ (ansible_memtotal_mb / 1000) | round(1) }}GB"

ag_motd_content: |

  --------------------------------------------------------------------------
                      This system is managed by Ansible
  --------------------------------------------------------------------------

  This is {{ ansible_fqdn }} running {{ ansible_distribution }}.

  NOTE: System and application configuration for this host is managed by
  automated systems. To ensure that any changes you make here are not lost,
  please contact with your system administrators.

  {% for item in ag_motd_info %}
  {% for key, value in item.items() | list %}
  {{ key }}{{ value }}
  {% endfor %}
  {% endfor %}

  Yours,
  {{ ag_motd_sysadmins_signature }}
  email: {{ ag_motd_sysadmins_email }}

  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  Last ansible run: {{ ansible_date_time.iso8601 }}
