---
galaxy_info:
  author: Adria Galin Figueras
  description: Set up message of the day (motd)
  company: Adria Galin
  license: GPLv3
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - system
dependencies: []
